spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./dados/copa
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

football:
  api:
    url: https://api.football-data.org/v4
    key: ${FOOTBALL_API_KEY}

server:
  error:
    include-message: always

